// Code generated by MockGen. DO NOT EDIT.
// Source: internal/customer/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/customer/repository.go -destination=internal/customer/mocks/customer_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	customer "backend-go/internal/customer"
	entities "backend-go/internal/entities"
	pagination "backend-go/pkg/pagination"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockRepositoryInterface is a mock of RepositoryInterface interface.
type MockRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockRepositoryInterfaceMockRecorder is the mock recorder for MockRepositoryInterface.
type MockRepositoryInterfaceMockRecorder struct {
	mock *MockRepositoryInterface
}

// NewMockRepositoryInterface creates a new mock instance.
func NewMockRepositoryInterface(ctrl *gomock.Controller) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryInterface) EXPECT() *MockRepositoryInterfaceMockRecorder {
	return m.recorder
}

// AddActivity mocks base method.
func (m *MockRepositoryInterface) AddActivity(tx *gorm.DB, a *customer.CustomerActivity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddActivity", tx, a)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddActivity indicates an expected call of AddActivity.
func (mr *MockRepositoryInterfaceMockRecorder) AddActivity(tx, a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddActivity", reflect.TypeOf((*MockRepositoryInterface)(nil).AddActivity), tx, a)
}

// AddAddress mocks base method.
func (m *MockRepositoryInterface) AddAddress(tx *gorm.DB, a *customer.CustomerAddress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAddress", tx, a)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddAddress indicates an expected call of AddAddress.
func (mr *MockRepositoryInterfaceMockRecorder) AddAddress(tx, a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAddress", reflect.TypeOf((*MockRepositoryInterface)(nil).AddAddress), tx, a)
}

// Create mocks base method.
func (m *MockRepositoryInterface) Create(tx *gorm.DB, c *customer.Customer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", tx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryInterfaceMockRecorder) Create(tx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepositoryInterface)(nil).Create), tx, c)
}

// Delete mocks base method.
func (m *MockRepositoryInterface) Delete(tx *gorm.DB, tenantID, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", tx, tenantID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryInterfaceMockRecorder) Delete(tx, tenantID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepositoryInterface)(nil).Delete), tx, tenantID, id)
}

// DeleteAddress mocks base method.
func (m *MockRepositoryInterface) DeleteAddress(tx *gorm.DB, tenantID, customerID, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAddress", tx, tenantID, customerID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAddress indicates an expected call of DeleteAddress.
func (mr *MockRepositoryInterfaceMockRecorder) DeleteAddress(tx, tenantID, customerID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAddress", reflect.TypeOf((*MockRepositoryInterface)(nil).DeleteAddress), tx, tenantID, customerID, id)
}

// GetByEmail mocks base method.
func (m *MockRepositoryInterface) GetByEmail(tx *gorm.DB, tenantID uuid.UUID, email string) (customer.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", tx, tenantID, email)
	ret0, _ := ret[0].(customer.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockRepositoryInterfaceMockRecorder) GetByEmail(tx, tenantID, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockRepositoryInterface)(nil).GetByEmail), tx, tenantID, email)
}

// GetByID mocks base method.
func (m *MockRepositoryInterface) GetByID(tx *gorm.DB, tenantID, id uuid.UUID) (customer.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", tx, tenantID, id)
	ret0, _ := ret[0].(customer.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRepositoryInterfaceMockRecorder) GetByID(tx, tenantID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetByID), tx, tenantID, id)
}

// List mocks base method.
func (m *MockRepositoryInterface) List(tx *gorm.DB, tenantID uuid.UUID, params *entities.ListParams) (pagination.Response[customer.Customer], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", tx, tenantID, params)
	ret0, _ := ret[0].(pagination.Response[customer.Customer])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRepositoryInterfaceMockRecorder) List(tx, tenantID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRepositoryInterface)(nil).List), tx, tenantID, params)
}

// ListActivities mocks base method.
func (m *MockRepositoryInterface) ListActivities(tx *gorm.DB, tenantID, customerID uuid.UUID, limit int) ([]customer.CustomerActivity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActivities", tx, tenantID, customerID, limit)
	ret0, _ := ret[0].([]customer.CustomerActivity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActivities indicates an expected call of ListActivities.
func (mr *MockRepositoryInterfaceMockRecorder) ListActivities(tx, tenantID, customerID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActivities", reflect.TypeOf((*MockRepositoryInterface)(nil).ListActivities), tx, tenantID, customerID, limit)
}

// RecordOrderStats mocks base method.
func (m *MockRepositoryInterface) RecordOrderStats(tx *gorm.DB, tenantID, id uuid.UUID, amount float64, orderAt any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordOrderStats", tx, tenantID, id, amount, orderAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordOrderStats indicates an expected call of RecordOrderStats.
func (mr *MockRepositoryInterfaceMockRecorder) RecordOrderStats(tx, tenantID, id, amount, orderAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordOrderStats", reflect.TypeOf((*MockRepositoryInterface)(nil).RecordOrderStats), tx, tenantID, id, amount, orderAt)
}

// Update mocks base method.
func (m *MockRepositoryInterface) Update(tx *gorm.DB, c *customer.Customer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", tx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryInterfaceMockRecorder) Update(tx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepositoryInterface)(nil).Update), tx, c)
}

// UpdateAddress mocks base method.
func (m *MockRepositoryInterface) UpdateAddress(tx *gorm.DB, tenantID, customerID uuid.UUID, a *customer.CustomerAddress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAddress", tx, tenantID, customerID, a)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAddress indicates an expected call of UpdateAddress.
func (mr *MockRepositoryInterfaceMockRecorder) UpdateAddress(tx, tenantID, customerID, a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAddress", reflect.TypeOf((*MockRepositoryInterface)(nil).UpdateAddress), tx, tenantID, customerID, a)
}
