// Code generated by MockGen. DO NOT EDIT.
// Source: internal/customer/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/customer/service.go -destination=internal/customer/mocks/customer_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	customer "backend-go/internal/customer"
	entities "backend-go/internal/entities"
	pagination "backend-go/pkg/pagination"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockServiceInterface is a mock of ServiceInterface interface.
type MockServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockServiceInterfaceMockRecorder is the mock recorder for MockServiceInterface.
type MockServiceInterfaceMockRecorder struct {
	mock *MockServiceInterface
}

// NewMockServiceInterface creates a new mock instance.
func NewMockServiceInterface(ctrl *gomock.Controller) *MockServiceInterface {
	mock := &MockServiceInterface{ctrl: ctrl}
	mock.recorder = &MockServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceInterface) EXPECT() *MockServiceInterfaceMockRecorder {
	return m.recorder
}

// AddActivity mocks base method.
func (m *MockServiceInterface) AddActivity(tx *gorm.DB, tenantID, customerID uuid.UUID, activityType, description string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddActivity", tx, tenantID, customerID, activityType, description)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddActivity indicates an expected call of AddActivity.
func (mr *MockServiceInterfaceMockRecorder) AddActivity(tx, tenantID, customerID, activityType, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddActivity", reflect.TypeOf((*MockServiceInterface)(nil).AddActivity), tx, tenantID, customerID, activityType, description)
}

// AddAddress mocks base method.
func (m *MockServiceInterface) AddAddress(ctx context.Context, tenantID uuid.UUID, customerID string, req *customer.AddressRequest) (customer.AddressResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAddress", ctx, tenantID, customerID, req)
	ret0, _ := ret[0].(customer.AddressResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddAddress indicates an expected call of AddAddress.
func (mr *MockServiceInterfaceMockRecorder) AddAddress(ctx, tenantID, customerID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAddress", reflect.TypeOf((*MockServiceInterface)(nil).AddAddress), ctx, tenantID, customerID, req)
}

// Create mocks base method.
func (m *MockServiceInterface) Create(ctx context.Context, tenantID uuid.UUID, req *customer.CreateCustomerRequest, userID string) (customer.CustomerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tenantID, req, userID)
	ret0, _ := ret[0].(customer.CustomerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockServiceInterfaceMockRecorder) Create(ctx, tenantID, req, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockServiceInterface)(nil).Create), ctx, tenantID, req, userID)
}

// Delete mocks base method.
func (m *MockServiceInterface) Delete(ctx context.Context, tenantID uuid.UUID, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, tenantID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockServiceInterfaceMockRecorder) Delete(ctx, tenantID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockServiceInterface)(nil).Delete), ctx, tenantID, id)
}

// FindOrCreateByEmail mocks base method.
func (m *MockServiceInterface) FindOrCreateByEmail(tx *gorm.DB, tenantID uuid.UUID, name, email string) (customer.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrCreateByEmail", tx, tenantID, name, email)
	ret0, _ := ret[0].(customer.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrCreateByEmail indicates an expected call of FindOrCreateByEmail.
func (mr *MockServiceInterfaceMockRecorder) FindOrCreateByEmail(tx, tenantID, name, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrCreateByEmail", reflect.TypeOf((*MockServiceInterface)(nil).FindOrCreateByEmail), tx, tenantID, name, email)
}

// GetActivities mocks base method.
func (m *MockServiceInterface) GetActivities(ctx context.Context, tenantID uuid.UUID, customerID string, limit int) ([]customer.ActivityResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActivities", ctx, tenantID, customerID, limit)
	ret0, _ := ret[0].([]customer.ActivityResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActivities indicates an expected call of GetActivities.
func (mr *MockServiceInterfaceMockRecorder) GetActivities(ctx, tenantID, customerID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActivities", reflect.TypeOf((*MockServiceInterface)(nil).GetActivities), ctx, tenantID, customerID, limit)
}

// GetByID mocks base method.
func (m *MockServiceInterface) GetByID(ctx context.Context, tenantID uuid.UUID, id string) (customer.CustomerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, tenantID, id)
	ret0, _ := ret[0].(customer.CustomerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockServiceInterfaceMockRecorder) GetByID(ctx, tenantID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockServiceInterface)(nil).GetByID), ctx, tenantID, id)
}

// List mocks base method.
func (m *MockServiceInterface) List(ctx context.Context, tenantID uuid.UUID, params *entities.ListParams) (pagination.Response[customer.CustomerResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, tenantID, params)
	ret0, _ := ret[0].(pagination.Response[customer.CustomerResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockServiceInterfaceMockRecorder) List(ctx, tenantID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockServiceInterface)(nil).List), ctx, tenantID, params)
}

// RecordOrderStats mocks base method.
func (m *MockServiceInterface) RecordOrderStats(tx *gorm.DB, tenantID, customerID uuid.UUID, amount float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordOrderStats", tx, tenantID, customerID, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordOrderStats indicates an expected call of RecordOrderStats.
func (mr *MockServiceInterfaceMockRecorder) RecordOrderStats(tx, tenantID, customerID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordOrderStats", reflect.TypeOf((*MockServiceInterface)(nil).RecordOrderStats), tx, tenantID, customerID, amount)
}

// Update mocks base method.
func (m *MockServiceInterface) Update(ctx context.Context, tenantID uuid.UUID, id string, req *customer.UpdateCustomerRequest, userID string) (customer.CustomerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, tenantID, id, req, userID)
	ret0, _ := ret[0].(customer.CustomerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockServiceInterfaceMockRecorder) Update(ctx, tenantID, id, req, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockServiceInterface)(nil).Update), ctx, tenantID, id, req, userID)
}
