// Code generated by MockGen. DO NOT EDIT.
// Source: internal/order/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/order/service.go -destination=internal/order/mocks/order_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	entities "backend-go/internal/entities"
	order "backend-go/internal/order"
	pagination "backend-go/pkg/pagination"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockServiceInterface is a mock of ServiceInterface interface.
type MockServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockServiceInterfaceMockRecorder is the mock recorder for MockServiceInterface.
type MockServiceInterfaceMockRecorder struct {
	mock *MockServiceInterface
}

// NewMockServiceInterface creates a new mock instance.
func NewMockServiceInterface(ctrl *gomock.Controller) *MockServiceInterface {
	mock := &MockServiceInterface{ctrl: ctrl}
	mock.recorder = &MockServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceInterface) EXPECT() *MockServiceInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockServiceInterface) Create(ctx context.Context, tenantID uuid.UUID, req *order.CreateOrderRequest, userID string) (order.OrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tenantID, req, userID)
	ret0, _ := ret[0].(order.OrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockServiceInterfaceMockRecorder) Create(ctx, tenantID, req, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockServiceInterface)(nil).Create), ctx, tenantID, req, userID)
}

// GetByID mocks base method.
func (m *MockServiceInterface) GetByID(ctx context.Context, tenantID uuid.UUID, id string) (order.OrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, tenantID, id)
	ret0, _ := ret[0].(order.OrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockServiceInterfaceMockRecorder) GetByID(ctx, tenantID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockServiceInterface)(nil).GetByID), ctx, tenantID, id)
}

// GetByIDRaw mocks base method.
func (m *MockServiceInterface) GetByIDRaw(tx *gorm.DB, tenantID, id uuid.UUID) (order.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDRaw", tx, tenantID, id)
	ret0, _ := ret[0].(order.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDRaw indicates an expected call of GetByIDRaw.
func (mr *MockServiceInterfaceMockRecorder) GetByIDRaw(tx, tenantID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDRaw", reflect.TypeOf((*MockServiceInterface)(nil).GetByIDRaw), tx, tenantID, id)
}

// List mocks base method.
func (m *MockServiceInterface) List(ctx context.Context, tenantID uuid.UUID, params *entities.ListParams) (pagination.Response[order.OrderResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, tenantID, params)
	ret0, _ := ret[0].(pagination.Response[order.OrderResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockServiceInterfaceMockRecorder) List(ctx, tenantID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockServiceInterface)(nil).List), ctx, tenantID, params)
}

// MarkFailed mocks base method.
func (m *MockServiceInterface) MarkFailed(tx *gorm.DB, tenantID, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkFailed", tx, tenantID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkFailed indicates an expected call of MarkFailed.
func (mr *MockServiceInterfaceMockRecorder) MarkFailed(tx, tenantID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFailed", reflect.TypeOf((*MockServiceInterface)(nil).MarkFailed), tx, tenantID, id)
}

// MarkPaid mocks base method.
func (m *MockServiceInterface) MarkPaid(tx *gorm.DB, tenantID, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkPaid", tx, tenantID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkPaid indicates an expected call of MarkPaid.
func (mr *MockServiceInterfaceMockRecorder) MarkPaid(tx, tenantID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPaid", reflect.TypeOf((*MockServiceInterface)(nil).MarkPaid), tx, tenantID, id)
}

// MarkRefunded mocks base method.
func (m *MockServiceInterface) MarkRefunded(tx *gorm.DB, tenantID, id uuid.UUID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkRefunded", tx, tenantID, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkRefunded indicates an expected call of MarkRefunded.
func (mr *MockServiceInterfaceMockRecorder) MarkRefunded(tx, tenantID, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkRefunded", reflect.TypeOf((*MockServiceInterface)(nil).MarkRefunded), tx, tenantID, id, userID)
}

// UpdateStatus mocks base method.
func (m *MockServiceInterface) UpdateStatus(ctx context.Context, tenantID uuid.UUID, id string, req *order.UpdateOrderStatusRequest, userID string) (order.OrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, tenantID, id, req, userID)
	ret0, _ := ret[0].(order.OrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockServiceInterfaceMockRecorder) UpdateStatus(ctx, tenantID, id, req, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockServiceInterface)(nil).UpdateStatus), ctx, tenantID, id, req, userID)
}
