// Code generated by MockGen. DO NOT EDIT.
// Source: internal/order/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/order/repository.go -destination=internal/order/mocks/order_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	entities "backend-go/internal/entities"
	order "backend-go/internal/order"
	pagination "backend-go/pkg/pagination"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockRepositoryInterface is a mock of RepositoryInterface interface.
type MockRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockRepositoryInterfaceMockRecorder is the mock recorder for MockRepositoryInterface.
type MockRepositoryInterfaceMockRecorder struct {
	mock *MockRepositoryInterface
}

// NewMockRepositoryInterface creates a new mock instance.
func NewMockRepositoryInterface(ctrl *gomock.Controller) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryInterface) EXPECT() *MockRepositoryInterfaceMockRecorder {
	return m.recorder
}

// AddTimeline mocks base method.
func (m *MockRepositoryInterface) AddTimeline(tx *gorm.DB, event *order.OrderTimeline) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTimeline", tx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTimeline indicates an expected call of AddTimeline.
func (mr *MockRepositoryInterfaceMockRecorder) AddTimeline(tx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTimeline", reflect.TypeOf((*MockRepositoryInterface)(nil).AddTimeline), tx, event)
}

// Create mocks base method.
func (m *MockRepositoryInterface) Create(tx *gorm.DB, arg1 *order.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", tx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryInterfaceMockRecorder) Create(tx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepositoryInterface)(nil).Create), tx, arg1)
}

// FindPendingPaymentOrder mocks base method.
func (m *MockRepositoryInterface) FindPendingPaymentOrder(tx *gorm.DB, tenantID, orderID uuid.UUID) (order.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPendingPaymentOrder", tx, tenantID, orderID)
	ret0, _ := ret[0].(order.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPendingPaymentOrder indicates an expected call of FindPendingPaymentOrder.
func (mr *MockRepositoryInterfaceMockRecorder) FindPendingPaymentOrder(tx, tenantID, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPendingPaymentOrder", reflect.TypeOf((*MockRepositoryInterface)(nil).FindPendingPaymentOrder), tx, tenantID, orderID)
}

// GetByID mocks base method.
func (m *MockRepositoryInterface) GetByID(tx *gorm.DB, tenantID, id uuid.UUID) (order.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", tx, tenantID, id)
	ret0, _ := ret[0].(order.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRepositoryInterfaceMockRecorder) GetByID(tx, tenantID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetByID), tx, tenantID, id)
}

// List mocks base method.
func (m *MockRepositoryInterface) List(tx *gorm.DB, tenantID uuid.UUID, params *entities.ListParams) (pagination.Response[order.Order], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", tx, tenantID, params)
	ret0, _ := ret[0].(pagination.Response[order.Order])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRepositoryInterfaceMockRecorder) List(tx, tenantID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRepositoryInterface)(nil).List), tx, tenantID, params)
}

// UpdatePaymentStatus mocks base method.
func (m *MockRepositoryInterface) UpdatePaymentStatus(tx *gorm.DB, tenantID, id uuid.UUID, status order.PaymentStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePaymentStatus", tx, tenantID, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePaymentStatus indicates an expected call of UpdatePaymentStatus.
func (mr *MockRepositoryInterfaceMockRecorder) UpdatePaymentStatus(tx, tenantID, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePaymentStatus", reflect.TypeOf((*MockRepositoryInterface)(nil).UpdatePaymentStatus), tx, tenantID, id, status)
}

// UpdateStatus mocks base method.
func (m *MockRepositoryInterface) UpdateStatus(tx *gorm.DB, tenantID, id uuid.UUID, status order.OrderStatus, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", tx, tenantID, id, status, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockRepositoryInterfaceMockRecorder) UpdateStatus(tx, tenantID, id, status, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockRepositoryInterface)(nil).UpdateStatus), tx, tenantID, id, status, userID)
}
