// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/storage/storage.go
//
// Generated by this command:
//
//	mockgen -source=pkg/storage/storage.go -destination=pkg/storage/mocks/storage.go -package=mocks Storage
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	multipart "mime/multipart"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
	isgomock struct{}
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockStorage) Delete(ctx context.Context, objectPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, objectPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockStorageMockRecorder) Delete(ctx, objectPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStorage)(nil).Delete), ctx, objectPath)
}

// GetPresignedURL mocks base method.
func (m *MockStorage) GetPresignedURL(ctx context.Context, objectName string, expiry time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPresignedURL", ctx, objectName, expiry)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPresignedURL indicates an expected call of GetPresignedURL.
func (mr *MockStorageMockRecorder) GetPresignedURL(ctx, objectName, expiry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPresignedURL", reflect.TypeOf((*MockStorage)(nil).GetPresignedURL), ctx, objectName, expiry)
}

// Upload mocks base method.
func (m *MockStorage) Upload(ctx context.Context, objectName string, reader io.Reader, size int64, contentType string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, objectName, reader, size, contentType)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockStorageMockRecorder) Upload(ctx, objectName, reader, size, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockStorage)(nil).Upload), ctx, objectName, reader, size, contentType)
}

// UploadMultipart mocks base method.
func (m *MockStorage) UploadMultipart(ctx context.Context, file *multipart.FileHeader, folder string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadMultipart", ctx, file, folder)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadMultipart indicates an expected call of UploadMultipart.
func (mr *MockStorageMockRecorder) UploadMultipart(ctx, file, folder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadMultipart", reflect.TypeOf((*MockStorage)(nil).UploadMultipart), ctx, file, folder)
}

// ValidateFileSafe mocks base method.
func (m *MockStorage) ValidateFileSafe(filename string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateFileSafe", filename)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateFileSafe indicates an expected call of ValidateFileSafe.
func (mr *MockStorageMockRecorder) ValidateFileSafe(filename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateFileSafe", reflect.TypeOf((*MockStorage)(nil).ValidateFileSafe), filename)
}
