// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"backend-go/internal/analytics"
	"backend-go/internal/auth"
	"backend-go/internal/category"
	"backend-go/internal/customer"
	"backend-go/internal/inventory"
	"backend-go/internal/order"
	"backend-go/internal/payment"
	"backend-go/internal/product"
	"backend-go/internal/review"
	"backend-go/internal/router"
	"backend-go/internal/setting"
	"backend-go/internal/tenant"
	"backend-go/internal/user"
	"backend-go/pkg/database"
	payment2 "backend-go/third_party/payment"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"github.com/sirupsen/logrus"
)

// Injectors from wire.go:

func Init(log *logrus.Logger) (*gin.Engine, func(), error) {
	db, cleanup, err := database.NewGormDB(log)
	if err != nil {
		return nil, nil, err
	}
	repositoryInterface := auth.NewRepository()
	serviceInterface := auth.NewService(db, repositoryInterface)
	handler := auth.NewHandler(serviceInterface)
	authRouter := auth.NewRouter(handler)
	tenantRepositoryInterface := tenant.NewRepository()
	tenantServiceInterface := tenant.NewService(db, tenantRepositoryInterface)
	tenantHandler := tenant.NewHandler(tenantServiceInterface)
	tenantRouter := tenant.NewRouter(tenantHandler)
	userRepositoryInterface := user.NewRepository()
	userServiceInterface := user.NewService(db, userRepositoryInterface)
	userHandler := user.NewHandler(userServiceInterface)
	userRouter := user.NewRouter(userHandler)
	categoryRepositoryInterface := category.NewRepository()
	categoryServiceInterface := category.NewService(db, categoryRepositoryInterface)
	categoryHandler := category.NewHandler(categoryServiceInterface)
	categoryRouter := category.NewRouter(categoryHandler)
	productRepositoryInterface := product.NewRepository()
	productServiceInterface := product.NewService(db, productRepositoryInterface)
	productHandler := product.NewHandler(productServiceInterface)
	productRouter := product.NewRouter(productHandler)
	customerRepositoryInterface := customer.NewRepository()
	customerServiceInterface := customer.NewService(db, customerRepositoryInterface)
	customerHandler := customer.NewHandler(customerServiceInterface)
	customerRouter := customer.NewRouter(customerHandler)
	orderRepositoryInterface := order.NewRepository()
	orderServiceInterface := order.NewService(db, orderRepositoryInterface, productServiceInterface, customerServiceInterface)
	orderHandler := order.NewHandler(orderServiceInterface)
	orderRouter := order.NewRouter(orderHandler)
	paymentRepositoryInterface := payment.NewRepository()
	string2 := MockProviderBaseURL()
	mockClient := payment2.NewMockClient(string2)
	paymentServiceInterface := payment.NewService(db, paymentRepositoryInterface, orderServiceInterface, mockClient)
	paymentHandler := payment.NewHandler(paymentServiceInterface)
	paymentRouter := payment.NewRouter(paymentHandler)
	inventoryRepositoryInterface := inventory.NewRepository()
	inventoryServiceInterface := inventory.NewService(db, inventoryRepositoryInterface, productServiceInterface)
	inventoryHandler := inventory.NewHandler(inventoryServiceInterface)
	inventoryRouter := inventory.NewRouter(inventoryHandler)
	settingRepositoryInterface := setting.NewRepository()
	settingServiceInterface := setting.NewService(db, settingRepositoryInterface)
	settingHandler := setting.NewHandler(settingServiceInterface)
	settingRouter := setting.NewRouter(settingHandler)
	analyticsServiceInterface := analytics.NewService(db)
	analyticsHandler := analytics.NewHandler(analyticsServiceInterface)
	analyticsRouter := analytics.NewRouter(analyticsHandler)
	reviewRepositoryInterface := review.NewRepository()
	reviewServiceInterface := review.NewService(db, reviewRepositoryInterface, productServiceInterface)
	reviewHandler := review.NewHandler(reviewServiceInterface)
	reviewRouter := review.NewRouter(reviewHandler)
	engine := router.NewGinEngine(db, authRouter, tenantRouter, userRouter, categoryRouter, productRouter, customerRouter, orderRouter, paymentRouter, inventoryRouter, settingRouter, analyticsRouter, reviewRouter)
	return engine, func() {
		cleanup()
	}, nil
}

// wire.go:

var authSet = wire.NewSet(auth.NewRepository, auth.NewService, auth.NewHandler, auth.NewRouter)

var tenantSet = wire.NewSet(tenant.NewRepository, tenant.NewService, tenant.NewHandler, tenant.NewRouter)

var userSet = wire.NewSet(user.NewRepository, user.NewService, user.NewHandler, user.NewRouter)

var categorySet = wire.NewSet(category.NewRepository, category.NewService, category.NewHandler, category.NewRouter)

var productSet = wire.NewSet(product.NewRepository, product.NewService, product.NewHandler, product.NewRouter)

var customerSet = wire.NewSet(customer.NewRepository, customer.NewService, customer.NewHandler, customer.NewRouter)

var orderSet = wire.NewSet(order.NewRepository, order.NewService, order.NewHandler, order.NewRouter)

var paymentSet = wire.NewSet(
	MockProviderBaseURL, payment2.NewMockClient, payment.NewRepository, payment.NewService, payment.NewHandler, payment.NewRouter, wire.Bind(new(payment2.ClientInterface), new(*payment2.MockClient)),
)

var inventorySet = wire.NewSet(inventory.NewRepository, inventory.NewService, inventory.NewHandler, inventory.NewRouter)

var settingSet = wire.NewSet(setting.NewRepository, setting.NewService, setting.NewHandler, setting.NewRouter)

var analyticsSet = wire.NewSet(analytics.NewService, analytics.NewHandler, analytics.NewRouter)

var reviewSet = wire.NewSet(review.NewRepository, review.NewService, review.NewHandler, review.NewRouter)
