// Code generated by MockGen. DO NOT EDIT.
// Source: internal/auth/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/auth/repository.go -destination=internal/auth/mocks/auth_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	auth "backend-go/internal/auth"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockRepositoryInterface is a mock of RepositoryInterface interface.
type MockRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockRepositoryInterfaceMockRecorder is the mock recorder for MockRepositoryInterface.
type MockRepositoryInterfaceMockRecorder struct {
	mock *MockRepositoryInterface
}

// NewMockRepositoryInterface creates a new mock instance.
func NewMockRepositoryInterface(ctrl *gomock.Controller) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryInterface) EXPECT() *MockRepositoryInterfaceMockRecorder {
	return m.recorder
}

// CreateRefreshToken mocks base method.
func (m *MockRepositoryInterface) CreateRefreshToken(tx *gorm.DB, token *auth.RefreshToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRefreshToken", tx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRefreshToken indicates an expected call of CreateRefreshToken.
func (mr *MockRepositoryInterfaceMockRecorder) CreateRefreshToken(tx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRefreshToken", reflect.TypeOf((*MockRepositoryInterface)(nil).CreateRefreshToken), tx, token)
}

// GetRefreshToken mocks base method.
func (m *MockRepositoryInterface) GetRefreshToken(tx *gorm.DB, tokenHash string) (auth.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshToken", tx, tokenHash)
	ret0, _ := ret[0].(auth.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefreshToken indicates an expected call of GetRefreshToken.
func (mr *MockRepositoryInterfaceMockRecorder) GetRefreshToken(tx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshToken", reflect.TypeOf((*MockRepositoryInterface)(nil).GetRefreshToken), tx, tokenHash)
}

// GetTenant mocks base method.
func (m *MockRepositoryInterface) GetTenant(tx *gorm.DB, id uuid.UUID) (auth.TenantBrief, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenant", tx, id)
	ret0, _ := ret[0].(auth.TenantBrief)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTenant indicates an expected call of GetTenant.
func (mr *MockRepositoryInterfaceMockRecorder) GetTenant(tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenant", reflect.TypeOf((*MockRepositoryInterface)(nil).GetTenant), tx, id)
}

// GetUserByEmail mocks base method.
func (m *MockRepositoryInterface) GetUserByEmail(tx *gorm.DB, email string) (auth.UserRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", tx, email)
	ret0, _ := ret[0].(auth.UserRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockRepositoryInterfaceMockRecorder) GetUserByEmail(tx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockRepositoryInterface)(nil).GetUserByEmail), tx, email)
}

// GetUserByID mocks base method.
func (m *MockRepositoryInterface) GetUserByID(tx *gorm.DB, id uuid.UUID) (auth.UserRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", tx, id)
	ret0, _ := ret[0].(auth.UserRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockRepositoryInterfaceMockRecorder) GetUserByID(tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetUserByID), tx, id)
}

// GetUserRoles mocks base method.
func (m *MockRepositoryInterface) GetUserRoles(tx *gorm.DB, userID uuid.UUID) ([]auth.RoleRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRoles", tx, userID)
	ret0, _ := ret[0].([]auth.RoleRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRoles indicates an expected call of GetUserRoles.
func (mr *MockRepositoryInterfaceMockRecorder) GetUserRoles(tx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRoles", reflect.TypeOf((*MockRepositoryInterface)(nil).GetUserRoles), tx, userID)
}

// RevokeRefreshToken mocks base method.
func (m *MockRepositoryInterface) RevokeRefreshToken(tx *gorm.DB, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeRefreshToken", tx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeRefreshToken indicates an expected call of RevokeRefreshToken.
func (mr *MockRepositoryInterfaceMockRecorder) RevokeRefreshToken(tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeRefreshToken", reflect.TypeOf((*MockRepositoryInterface)(nil).RevokeRefreshToken), tx, id)
}

// UpdateLastLogin mocks base method.
func (m *MockRepositoryInterface) UpdateLastLogin(tx *gorm.DB, userID uuid.UUID, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastLogin", tx, userID, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastLogin indicates an expected call of UpdateLastLogin.
func (mr *MockRepositoryInterfaceMockRecorder) UpdateLastLogin(tx, userID, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastLogin", reflect.TypeOf((*MockRepositoryInterface)(nil).UpdateLastLogin), tx, userID, at)
}
