// Code generated by MockGen. DO NOT EDIT.
// Source: internal/product/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/product/service.go -destination=internal/product/mocks/product_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	entities "backend-go/internal/entities"
	product "backend-go/internal/product"
	pagination "backend-go/pkg/pagination"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockServiceInterface is a mock of ServiceInterface interface.
type MockServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockServiceInterfaceMockRecorder is the mock recorder for MockServiceInterface.
type MockServiceInterfaceMockRecorder struct {
	mock *MockServiceInterface
}

// NewMockServiceInterface creates a new mock instance.
func NewMockServiceInterface(ctrl *gomock.Controller) *MockServiceInterface {
	mock := &MockServiceInterface{ctrl: ctrl}
	mock.recorder = &MockServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceInterface) EXPECT() *MockServiceInterfaceMockRecorder {
	return m.recorder
}

// AddStock mocks base method.
func (m *MockServiceInterface) AddStock(tx *gorm.DB, tenantID, id uuid.UUID, qty int, incoming bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddStock", tx, tenantID, id, qty, incoming)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddStock indicates an expected call of AddStock.
func (mr *MockServiceInterfaceMockRecorder) AddStock(tx, tenantID, id, qty, incoming any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddStock", reflect.TypeOf((*MockServiceInterface)(nil).AddStock), tx, tenantID, id, qty, incoming)
}

// Create mocks base method.
func (m *MockServiceInterface) Create(ctx context.Context, tenantID uuid.UUID, req *product.CreateProductRequest, userID string) (product.ProductResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tenantID, req, userID)
	ret0, _ := ret[0].(product.ProductResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockServiceInterfaceMockRecorder) Create(ctx, tenantID, req, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockServiceInterface)(nil).Create), ctx, tenantID, req, userID)
}

// Delete mocks base method.
func (m *MockServiceInterface) Delete(ctx context.Context, tenantID uuid.UUID, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, tenantID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockServiceInterfaceMockRecorder) Delete(ctx, tenantID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockServiceInterface)(nil).Delete), ctx, tenantID, id)
}

// GetByID mocks base method.
func (m *MockServiceInterface) GetByID(ctx context.Context, tenantID uuid.UUID, id string) (product.ProductResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, tenantID, id)
	ret0, _ := ret[0].(product.ProductResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockServiceInterfaceMockRecorder) GetByID(ctx, tenantID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockServiceInterface)(nil).GetByID), ctx, tenantID, id)
}

// GetByIDRaw mocks base method.
func (m *MockServiceInterface) GetByIDRaw(tx *gorm.DB, tenantID, id uuid.UUID) (product.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDRaw", tx, tenantID, id)
	ret0, _ := ret[0].(product.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDRaw indicates an expected call of GetByIDRaw.
func (mr *MockServiceInterfaceMockRecorder) GetByIDRaw(tx, tenantID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDRaw", reflect.TypeOf((*MockServiceInterface)(nil).GetByIDRaw), tx, tenantID, id)
}

// GetBySKU mocks base method.
func (m *MockServiceInterface) GetBySKU(tx *gorm.DB, tenantID uuid.UUID, sku string) (product.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySKU", tx, tenantID, sku)
	ret0, _ := ret[0].(product.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySKU indicates an expected call of GetBySKU.
func (mr *MockServiceInterfaceMockRecorder) GetBySKU(tx, tenantID, sku any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySKU", reflect.TypeOf((*MockServiceInterface)(nil).GetBySKU), tx, tenantID, sku)
}

// List mocks base method.
func (m *MockServiceInterface) List(ctx context.Context, tenantID uuid.UUID, params *entities.ListParams) (pagination.Response[product.ProductResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, tenantID, params)
	ret0, _ := ret[0].(pagination.Response[product.ProductResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockServiceInterfaceMockRecorder) List(ctx, tenantID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockServiceInterface)(nil).List), ctx, tenantID, params)
}

// ReleaseReserved mocks base method.
func (m *MockServiceInterface) ReleaseReserved(tx *gorm.DB, tenantID, id uuid.UUID, qty int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseReserved", tx, tenantID, id, qty)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseReserved indicates an expected call of ReleaseReserved.
func (mr *MockServiceInterfaceMockRecorder) ReleaseReserved(tx, tenantID, id, qty any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseReserved", reflect.TypeOf((*MockServiceInterface)(nil).ReleaseReserved), tx, tenantID, id, qty)
}

// ReserveStock mocks base method.
func (m *MockServiceInterface) ReserveStock(tx *gorm.DB, tenantID, id uuid.UUID, qty int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReserveStock", tx, tenantID, id, qty)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReserveStock indicates an expected call of ReserveStock.
func (mr *MockServiceInterfaceMockRecorder) ReserveStock(tx, tenantID, id, qty any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReserveStock", reflect.TypeOf((*MockServiceInterface)(nil).ReserveStock), tx, tenantID, id, qty)
}

// RestoreStock mocks base method.
func (m *MockServiceInterface) RestoreStock(tx *gorm.DB, tenantID, id uuid.UUID, qty int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreStock", tx, tenantID, id, qty)
	ret0, _ := ret[0].(error)
	return ret0
}

// RestoreStock indicates an expected call of RestoreStock.
func (mr *MockServiceInterfaceMockRecorder) RestoreStock(tx, tenantID, id, qty any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreStock", reflect.TypeOf((*MockServiceInterface)(nil).RestoreStock), tx, tenantID, id, qty)
}

// Update mocks base method.
func (m *MockServiceInterface) Update(ctx context.Context, tenantID uuid.UUID, id string, req *product.UpdateProductRequest, userID string) (product.ProductResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, tenantID, id, req, userID)
	ret0, _ := ret[0].(product.ProductResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockServiceInterfaceMockRecorder) Update(ctx, tenantID, id, req, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockServiceInterface)(nil).Update), ctx, tenantID, id, req, userID)
}

// UpdateRating mocks base method.
func (m *MockServiceInterface) UpdateRating(tx *gorm.DB, tenantID, id uuid.UUID, rating float64, reviewCount int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRating", tx, tenantID, id, rating, reviewCount)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRating indicates an expected call of UpdateRating.
func (mr *MockServiceInterfaceMockRecorder) UpdateRating(tx, tenantID, id, rating, reviewCount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRating", reflect.TypeOf((*MockServiceInterface)(nil).UpdateRating), tx, tenantID, id, rating, reviewCount)
}
