// Code generated by MockGen. DO NOT EDIT.
// Source: internal/product/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/product/repository.go -destination=internal/product/mocks/product_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	entities "backend-go/internal/entities"
	product "backend-go/internal/product"
	pagination "backend-go/pkg/pagination"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockRepositoryInterface is a mock of RepositoryInterface interface.
type MockRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockRepositoryInterfaceMockRecorder is the mock recorder for MockRepositoryInterface.
type MockRepositoryInterfaceMockRecorder struct {
	mock *MockRepositoryInterface
}

// NewMockRepositoryInterface creates a new mock instance.
func NewMockRepositoryInterface(ctrl *gomock.Controller) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryInterface) EXPECT() *MockRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepositoryInterface) Create(tx *gorm.DB, arg1 *product.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", tx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryInterfaceMockRecorder) Create(tx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepositoryInterface)(nil).Create), tx, arg1)
}

// Delete mocks base method.
func (m *MockRepositoryInterface) Delete(tx *gorm.DB, tenantID, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", tx, tenantID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryInterfaceMockRecorder) Delete(tx, tenantID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepositoryInterface)(nil).Delete), tx, tenantID, id)
}

// GetByID mocks base method.
func (m *MockRepositoryInterface) GetByID(tx *gorm.DB, tenantID, id uuid.UUID) (product.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", tx, tenantID, id)
	ret0, _ := ret[0].(product.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRepositoryInterfaceMockRecorder) GetByID(tx, tenantID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetByID), tx, tenantID, id)
}

// GetBySKU mocks base method.
func (m *MockRepositoryInterface) GetBySKU(tx *gorm.DB, tenantID uuid.UUID, sku string) (product.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySKU", tx, tenantID, sku)
	ret0, _ := ret[0].(product.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySKU indicates an expected call of GetBySKU.
func (mr *MockRepositoryInterfaceMockRecorder) GetBySKU(tx, tenantID, sku any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySKU", reflect.TypeOf((*MockRepositoryInterface)(nil).GetBySKU), tx, tenantID, sku)
}

// List mocks base method.
func (m *MockRepositoryInterface) List(tx *gorm.DB, tenantID uuid.UUID, params *entities.ListParams) (pagination.Response[product.Product], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", tx, tenantID, params)
	ret0, _ := ret[0].(pagination.Response[product.Product])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRepositoryInterfaceMockRecorder) List(tx, tenantID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRepositoryInterface)(nil).List), tx, tenantID, params)
}

// ReplaceImages mocks base method.
func (m *MockRepositoryInterface) ReplaceImages(tx *gorm.DB, productID uuid.UUID, urls []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceImages", tx, productID, urls)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceImages indicates an expected call of ReplaceImages.
func (mr *MockRepositoryInterfaceMockRecorder) ReplaceImages(tx, productID, urls any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceImages", reflect.TypeOf((*MockRepositoryInterface)(nil).ReplaceImages), tx, productID, urls)
}

// Update mocks base method.
func (m *MockRepositoryInterface) Update(tx *gorm.DB, arg1 *product.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", tx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryInterfaceMockRecorder) Update(tx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepositoryInterface)(nil).Update), tx, arg1)
}

// UpdateRating mocks base method.
func (m *MockRepositoryInterface) UpdateRating(tx *gorm.DB, tenantID, productID uuid.UUID, rating float64, reviewCount int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRating", tx, tenantID, productID, rating, reviewCount)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRating indicates an expected call of UpdateRating.
func (mr *MockRepositoryInterfaceMockRecorder) UpdateRating(tx, tenantID, productID, rating, reviewCount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRating", reflect.TypeOf((*MockRepositoryInterface)(nil).UpdateRating), tx, tenantID, productID, rating, reviewCount)
}
